FLEET_NAME = "tb3_lab"

UPSTREAM_ROBOT = "tb3_1"
DOWNSTREAM_ROBOT = "tb3_2"

SOURCE_WAYPOINT = "source"
STAGING_WAYPOINT = "staging"
TRANSFER_WAYPOINT = "transfer"
TRANSFER_UPSTREAM_EXIT_WAYPOINT = "upstream_exit"
TRANSFER_DOWNSTREAM_EXIT_WAYPOINT = "downstream_exit"
DESTINATION_WAYPOINT = "destination"

UPSTREAM_HOME_WAYPOINT = "robot1_home"
DOWNSTREAM_HOME_WAYPOINT = "robot2_home"

REQUESTER = "mission_manager"
