<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>macmoi_free_fleet_bringup</name>
  <version>0.0.0</version>
  <description>Free fleet bringup package for the AIML Lab deployment.</description>
  <maintainer email="quangminh6624@gmail.com">minhqphan</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>free_fleet_adapter</exec_depend>
  <exec_depend>macmoi_assets</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
