rmf_fleet:
  name: "tb3_lab"
  limits:
    linear: [0.3, 3.0]
    angular: [1.0, 3.2]
  profile:
    footprint: 0.22
    vicinity: 0.5
  reversible: true
  battery_system:
    voltage: 12.0
    capacity: 18.0
    charging_current: 1.0
  mechanical_system:
    mass: 3.0
    moment_of_inertia: 0.05
    friction_coefficient: 0.22
  ambient_system:
    power: 8.0
  tool_system:
    power: 0.0
  recharge_threshold: 0.15
  recharge_soc: 1.0
  publish_fleet_state: 10.0
  account_for_battery_drain: true
  task_capabilities:
    loop: true
    delivery: false
  finishing_request: "charge"
  responsive_wait: true
  robots:
    tb3_1:
      charger: "robot1_home"
      responsive_wait: true
      navigation_stack: 2
      init_timeout_sec: 30
      initial_map: "LG"
      map_frame: "map"
      robot_frame: "base_footprint"
      maps:
        LG:
          map_url: "../../maps/aiml_lab.yaml"

    # tb3_2:
    #   charger: "robot2_home"
    #   responsive_wait: false
    #   navigation_stack: 2
    #   init_timeout_sec: 30
    #   initial_map: "LG"
    #   map_frame: "map"
    #   robot_frame: "base_footprint"
    #   maps:
    #     LG:
    #       map_url: "../../maps/aiml_lab.yaml"
  robot_state_update_frequency: 10.0

reference_coordinates:
  LG:
    rmf:
      - [12.854374871984213, -3.8726671555069916]
      - [12.942662582931954, -5.815638350433473]
      - [10.14306864533869, -5.029635906462173]
      - [15.759973283091028, -5.1444247357883]
    robot:
      - [-0.5594, 2.0784]
      - [-0.4699, 0.1098]
      - [-3.3064, 0.9062]
      - [2.3845, 0.7899]
